### ISSUE TITLE
Best promotion doesn't apply everytime

### ISSUE THREAD

**Issue by VickySteeves** [2020-nyu-devops/promotions#42]
### Assumptions
- There is at least one product
- There is at least two active promotion that applies to the product, with one that saves more money than the other
- Only 1 promotion can be applied to a product at a time

### Acceptance Criteria
- When given a product and a set of active promotions, the promotions service returns the promotion that has the biggest discount

**Comment by sukumarh** [comment]
Additional details regarding implementation:
1. The API is of the form ``` /promotions/apply?product_id=product_price ``` where **product_price** is the price for single quantity of the product. 
2. This returns the recommended *promo_code* (which will maximize the discount for the user). The ``` query ``` service can then be used to fetch all the details of the promotion. One promotion is recommended for each product passed into the query string.
3. In case of promotion type *BOGO*, the discount is considered as 50% since the quantity of the products is not considered by the API.
